-- Удаление всех таблиц
DROP TABLE IF EXISTS Checklist2task CASCADE;
DROP TABLE IF EXISTS Checklist_task CASCADE;
DROP TABLE IF EXISTS Checklist CASCADE;
DROP TABLE IF EXISTS Notifications CASCADE;
DROP TABLE IF EXISTS TimeInterval CASCADE;
DROP TABLE IF EXISTS Board_s_task CASCADE;
DROP TABLE IF EXISTS Task CASCADE;
DROP TABLE IF EXISTS Board_subscribers CASCADE;
DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Board CASCADE;
